App\Entity\Customer: 
  attributes:
    normalization_context:
        groups: ["customer:read"]
  # collectionOperations:
  #   get: ~
      # normalization_context:
      #   groups: ["customer:read"]
  # itemOperations:
  #   get: 
  #   delete: ~